# GMM Estimation of Mean-Variance Frontier

These notes are about how we can use GMM and the delta method to estimate a mean-variance frontier and also calculate a confidence band for the frontier. The purpose is to provide a quick repetition of GMM and the delta method - and to teach you how to implement it in Python. The approach in these notes is threfore very practical. 

## GMM Estimation of Means and Covariance Matrices

Let $R_t$ be a vector of net returns of $N$ assets. We want to estimate the mean vector and the covariance matrix. The moment conditions for the mean vector are:

$$
\mathbb{E}[R_t] - \mu = 0_{N\times1}
$$ {#eq-1}

and the moment conditions for the second moment matrix are:

$$
\mathbb{E} R_t R^{'}_t-\Gamma = 0_{N \times N}
$$ {#eq-2}

Example 1. With $N=2$ we have:

$$
\mathbb{E} \begin{bmatrix}
R_{1t} \\
R_{2t}
\end{bmatrix} - \begin{bmatrix}
\mu_1 \\
\mu_2
\end{bmatrix} = \begin{bmatrix}
0 \\
0
\end{bmatrix}
$$ {#eq-3}

and 

$$
\mathbb{E}\begin{bmatrix}
R^2_{1t} & R_{1t}R_{2t} \\
R_{2t}R_{1t} & R^2_{2t}
\end{bmatrix}
-
\begin{bmatrix}
\Gamma_{11} & \Gamma_{12} \\
\Gamma_{21} & \Gamma_{22}
\end{bmatrix} = 
\begin{bmatrix}
0 & 0 \\
0 & 0
\end{bmatrix}
$$ {#eq-4}

The second moment matrix is symmetrix and contains therefore only $N(N+1)/2$ unique elements. Although there is some book keeping involved in getting rid of the non-unique elements (and then getting back to the full second moment matrix again), it is often worth the troube - in particular if we later want to apply the delta method (take derivatives with respect to the parameters). The standard way of doing that is through the $\text{vech}$ operator.

Remark 2. (The vech operator). $\text{vech}(A)$ where $A$ is $m \times m$ gives an $m(m+1)/2 \times 1$ vector with the elements on and below the principal diagonal $A$ stacked on top of each other (column wise). For instance:

$$
\text{vech} \begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix} = 
\begin{bmatrix}
a_{11} \\
a_{21} \\
a_{22}
\end{bmatrix}
$$ {#eq-5}

Remark 3. (Duplication matrix). The duplication matrix $D_m$ is defined such that for any symmetric $m \times m$ matrix $A$ we have $vec(A) = D_m \text{vech}(A)$. The duplication matrix is therefore useful for "inverting" the vech operator (the step from $\text{vec}(A)$ to $A^{'}$ is trivial). For instance, to continue the example of the vech operator:

$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
a_{11} \\
a_{21} \\
a_{22}
\end{bmatrix}
= \begin{bmatrix}
a_{11} \\ 
a_{21} \\
a_{21} \\
a_{22}
\end{bmatrix}
$$ {#eq-6}

or
 
$$
D_2 \text{vech}(A) = \text{vec}(A)
$$ {#eq-7}

We therefore pick out the unique elements in $$\mathbb{E}R_t R^{'}_t - \Gamma = 0_{N \times N}$$ by:

$$
E \text{vech}(R_t R^{'}_t) - \text{vech}(\Gamma) = 0_{N(N+1)/2\times1}
$$ {#eq-8}


Example 4. Continuing the previous example, we get:
$$
\mathbb{E} \begin{bmatrix}
R^2_{1t} \\
R_{2t}R_{1t} \\
R^2_{2t}
\end{bmatrix}
- \begin{bmatrix}
\Gamma_{11} \\
\Gamma_{21} \\
\Gamma_{22}
\end{bmatrix}
= \begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
$$ {#eq-9}

Stacking the first equation and the previous one, and substitute the sample mean for the population expectation to get the GMM estimator:

$$
\frac{1}{T} \sum^T_{t=1} \begin{bmatrix} R_t \\
\text{vech}(R_tR^{'}_t)
\end{bmatrix}
- \begin{bmatrix}
\hat{\mu}
\text{vech}(\hat{\Gamma})
\end{bmatrix}
= \begin{bmatrix}
0_{N\times1} \\
0_{N(N+1)/2\times1}
\end{bmatrix}
$$ {#eq-10}

or 

$$
\frac{1}{T} \sum^{T}_{t=1} x_t - \hat{\beta} = 0
$$

Remark 5 (Python coding). Let $R$ be a $T \times N$ matrix with $R^{'}_t$ in row $t$. 
Let $Z$ be a $T \times N(N+1)/2$ matrix with $\text{vech}(R_tR^{'}_t)'$ in row $t$. 
Then 

```{python}
import numpy as np

def vech(M):
    """Stack the lower triangle of M column by column."""
    r, c = np.triu_indices(M.shape[0])
    return M.T[r, c]

R = np.array([[1., 2.], [3., 4.], [5., 6.]])
print(np.outer(R[1], R[1]))
print(vech(np.outer(R[1], R[1])))
```



## Asymptotic Distribution of the GMM Estimators

To reproduce.

## Mean-Variance Frontier

To reproduce.
